[main]
listen=[::0]:25,[::0]:587
nodes=4
daemonize=false
max_connections=100
timeout=300
max_recipients=100
max_received_count=100

; me = the hostname Haraka uses in EHLO and Received headers
me=mail.mailspark.online

[headers]
add_received=true
show_version=false
